### PR TITLE
Wire develop

### PR DESCRIPTION
**Pull request by KurtE**
Make a version of Wire library that used hardware I2C objects.
This includes the default one that was using bitbang

As well as Wire1 which uses pins 50, 51 of expansion connector.

Also support hopefully for Wire Slave objects. 

This is the work that I have been doing as part of the issue:
https://github.com/ROBOTIS-GIT/OpenCR/issues/107

Thought it might make sense now to create it as a pull request, so you might be able to start reviewing it and or testing it out. 

Let me know if you would like any changes made. 

Thanks
Kurt

### CODE REVIEW

**Comment by OpusK** [comment]
@KurtE, thanks for your contributions!


I have tested [the example](https://github.com/adafruit/Adafruit-MLX90614-Library) with your code. (after connecting the actual hardware).
However, the board can not read the sensor value.

Do you have an [MLX90614](https://github.com/adafruit/Adafruit-MLX90614-Library) sensor?
Or if there is a sensor being used in the Arduino libraries, I think it would be better to test the I2C with the sensor.

I think we'll have to check to see what the problem is.

**Comment by KurtE** [comment]
Nope I don't have any of the MLX sensors. which one do you have? Adafruit sells two of them (3v and 5v)...   I assume you have hooked up with PU resistors.  

Currently I have issues buying stuff from Adafruit, as they don't want to ship to my mailing address... Amazon does sell a few different versions.  Ordered [one ]( https://smile.amazon.com/SMAKN%C2%AE-MLX90614ESF-non-contact-infrared-temperature/dp/B01CORD2HY/ref=sr_1_4?rps=1&ie=UTF8&qid=1530798842&sr=8-4&keywords=MLX90614&refinements=p_85%3A2470955011)
Mainly ordered that one as it has an LDO power supply.  Should arrive in a few days.

**Comment by KurtE** [comment]
I now have one of these sensors.  Found there is an issue, in particular the call
Wire.endtrasmission(false);

Fails to output anything and errors out.  (I did say I needed an example of this ;) 
Sending True instead the I2C output, but still no valid data... so debugging, the device might require a restart on the read.

**Comment by KurtE** [comment]
@OpusK,
I believe the issue with the temperature sensor has been fixed.  The code now remembers if the last call to endTransmission or requestFrom issued a sendStop or not.  If not the call will not abort if the I2C Buss is busy (as it should be busy if we did not send stop). 

This appears to have fixed the example mlxtest program.  

After the change, I reran, the Scanner test, plus CMPS03 test, plus SSD1306 test

**Comment by OpusK** [comment]
Sorry for the delay.
I respect your passion.

I checked with mlxtest that it works without problems.
I have also confirmed that it works well with other I2C sensors.

Thank you again for your passion and contributions.

**Pull request merged**
