### PR TITLE
Add support for precompiled libraries

### PR DESCRIPTION
**Pull request by pablogs9**
This PR adds support for precompiled libraries in OpenCR Arduino platform.

**Purpose:** 
At [micro-ROS](https://micro-ros.github.io/) we are developing a port of our libraries to your platform that can be integrated into the Arduino IDE. Due to the complexity of the ROS 2 build system, we are providing it as pre-compiled library ([check here for more details](https://arduino.github.io/arduino-cli/library-specification/)).

Currently, if you try to build an OpenCR project with a pre-compiled library you obtain:

```bash
The platform does not support 'compiler.libraries.ldflags' for pre-compiled libraries.
```

So in order to provide support, we are adding an empty `compiler.libraries.ldflags` variable (that will be filled automatically by the Arduino IDE when it found precompiled libraries) to your `platform.txt`.

Related: https://github.com/micro-ROS/micro_ros_arduino

### CODE REVIEW

**Comment by ROBOTIS-Will** [comment]
Hi @pablogs9 Thank you for your contribution. I'll merge this into our develop branch first then merge into the master.

**Comment by pablogs9** [comment]
Hi @ROBOTIS-Will, thanks. Do you know when are you going to release a new tagged version approximately?

**Comment by ROBOTIS-Will** [comment]
@pablogs9 
I'm also preparing for the TurtleBot3 firmware updates for ROS1 Noetic at the same time and will be merged into the master by tomorrow at the latest.
Thank you.

**Comment by pablogs9** [comment]
Awesome, thanks for the quick response!

**Pull request merged**
